services:
  frontend:
    build: animal_news_frontend/.
    image: ntnhatanh2001/animal_news_frontend:latest
    ports:
      - 3001:3000
    depends_on:
      - backend

  backend:
    build: animal_news_backend/.
    image: ntnhatanh2001/animal_news_backend:latest
    ports:
      - 8081:8080
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  proxy:
    image: 'nginx:alpine'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
