services:
  frontend:
    build: animal_news_frontend/.
    image: ntnhatanh2001/animal_news_frontend:latest
    ports:
      - 3001:3000
    depends_on:
      - backend

  backend:
    build: animal_news_backend/.
    image: ntnhatanh2001/animal_news_backend:latest
    ports:
      - 8081:8080
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DB=$MYSQL_DB
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD


  proxy:
    image: 'nginx:alpine'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './ssl-params.conf:/etc/nginx/snippets/ssl-params.conf'
      - './self-signed.conf:/etc/nginx/snippets/self-signed.conf'
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
