services:
  frontend:
    build: animal_news_frontend/.
    ports:
      - 3001:3000
    depends_on:
      - backend

  backend:
    build: animal_news_backend/.
    ports:
      - 8081:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    image: 'nginx:alpine'
    volumes:
      - 'default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
