spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:animal_news}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  flyway:
    enabled: true
    locations: classpath:db/migration

crawler:
  args:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    user: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    database: ${MYSQL_DB:animal_news}
  script-directory: ./animal-crawler
  pushing-to-git-script-directory: ./animal-crawler/public
