# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animal_news
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  flyway:
    enabled: true
    locations: classpath:db/migration
